/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import controladores.SolicitudJpaControl;
import java.util.List;
import modelos.SolicitudEvento;
import utiles.JPAUtil;
import utiles.ModeloGenericoTabla;

/**
 *
 * @author domen
 */
public class ConsultaSolicitudes extends javax.swing.JPanel {

    SolicitudJpaControl controlEvento = new SolicitudJpaControl(JPAUtil.getEntityManagerFactory());
    SolicitudEvento evento;
    ModeloGenericoTabla ModeloTabla;

    /**
     * Creates new form AdministradorEventos
     */
    public ConsultaSolicitudes() {
        initComponents();
        this.cargarDatosTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEventos = new javax.swing.JTable();

        tablaEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "N°", "Evento", "Fecha", "Hora", "Lugar"
            }
        ));
        jScrollPane1.setViewportView(tablaEventos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void cargarDatosTabla() {
        List eventos = null;
        eventos = controlEvento.consultarTodos();

        try {
            String[] Columnas = new String[]{"Nombre", "Tipo de evento", "fecha", "hora", "ubicacion", "numeroAsistentes", "descripcion"};
            String[] filas = new String[]{"nombre", "tipoEvento", "fecha", "hora", "ubicacion", "numeroAsistentes", "descripcion"};
            this.ModeloTabla = new ModeloGenericoTabla(Columnas, filas, eventos);
            this.tablaEventos.setModel(ModeloTabla);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEventos;
    // End of variables declaration//GEN-END:variables
}
