/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import controladores.EventoJpaControl;
import java.awt.Component;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;
import modelos.Evento;
import utiles.JPAUtil;
import utiles.ModeloGenericoTabla;

/**
 *
 * @author domen
 */
public class ConsultaEvento extends javax.swing.JPanel {

    private static void eliminarCarrera(int idEvento) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    EventoJpaControl controlEvento = new EventoJpaControl(JPAUtil.getEntityManagerFactory());
    Evento evento;
    ModeloGenericoTabla ModeloTabla;

    /**
     * Creates new form AdministradorEventos
     */
    public ConsultaEvento() {
        initComponents();
        this.cargarDatosTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEventos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bModificar = new javax.swing.JButton();
        BotonEliminarRenderer = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        bCrear = new javax.swing.JButton();

        tablaEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "N°", "Evento", "Fecha", "Hora", "Lugar"
            }
        ));
        jScrollPane1.setViewportView(tablaEventos);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setText("Administración");

        bModificar.setText("Modificar");

        BotonEliminarRenderer.setText("Eliminar");
        BotonEliminarRenderer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarRendererActionPerformed(evt);
            }
        });

        bSalir.setText("Salir");

        bCrear.setText("Crear");
        bCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonEliminarRenderer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8)))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bCrear)
                .addGap(12, 12, 12)
                .addComponent(bModificar)
                .addGap(18, 18, 18)
                .addComponent(BotonEliminarRenderer)
                .addGap(12, 12, 12)
                .addComponent(bSalir)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearActionPerformed
        // TODO add your handling code here:
        JInternalFrame jif1 = (JInternalFrame)SwingUtilities.getAncestorOfClass(JInternalFrame.class, this);
        if (jif1!=null) {
            jif1.setVisible(false);
            jif1.dispose();
        }
        
        JInternalFrame subVentana= new JInternalFrame("Crear Evento", true, true);
        CrearEvento evento= new CrearEvento();
        subVentana.add(evento);
        subVentana.pack();
        subVentana.setVisible(true);
        System.out.println("Llamamos a la ventana Evento");
        
    }//GEN-LAST:event_bCrearActionPerformed

    private void BotonEliminarRendererActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarRendererActionPerformed
        // TODO add your handling code here:
        evento=obtenerEventoSeleccionada();
        try{
            if(evento!=null){
                ConsultaEvento.eliminarCarrera(evento.getIdEvento());
                cargarDatosTabla();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "No selecciono el elmento de la tabla");
            e.printStackTrace();
        }
    }//GEN-LAST:event_BotonEliminarRendererActionPerformed
    private void cargarDatosTabla() {
        List eventos = null;
        eventos = controlEvento.consultarTodos();

        try {
            String[] Columnas = new String[]{"Nombre", "Tipo de evento", "fecha", "hora", "ubicacion", "numeroAsistentes", "descripcion"};
            String[] filas = new String[]{"nombre", "tipoEvento", "fecha", "hora", "ubicacion", "numeroAsistentes", "descripcion"};
            this.ModeloTabla = new ModeloGenericoTabla(Columnas, filas, eventos);
            this.tablaEventos.setModel(ModeloTabla);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void agregarBotonEliminar() {
        TableColumn columnaEliminar = tablaEventos.getColumnModel().getColumn(tablaEventos.getColumnCount() - 1);
        columnaEliminar.setCellRenderer(new BotonEliminarRenderer());
    }

    private Evento obtenerEventoSeleccionada() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private class BotonEliminarRenderer extends DefaultTableCellRenderer {
        private JButton botonEliminar = new JButton("Eliminar");

        public BotonEliminarRenderer() {
            botonEliminar.addActionListener(e -> {
                // Aquí puedes implementar la lógica para eliminar el evento
                // Por ejemplo:
                int fila = tablaEventos.getSelectedRow();
                if (fila != -1) {
                    // Eliminar la fila correspondiente del modelo de la tabla
                }
            });
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            return botonEliminar;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEliminarRenderer;
    private javax.swing.JButton bCrear;
    private javax.swing.JButton bModificar;
    private javax.swing.JButton bSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEventos;
    // End of variables declaration//GEN-END:variables
}
